
Epoch: 0
Traceback (most recent call last):
  File "/Users/simonknudsen/Desktop/final_exercise/main.py", line 97, in <module>
    cli()
  File "/Users/simonknudsen/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simonknudsen/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simonknudsen/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simonknudsen/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simonknudsen/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simonknudsen/Desktop/final_exercise/main.py", line 56, in train
    logimage = transforms.ToTensor(images)
TypeError: __init__() takes 1 positional argument but 2 were given